<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/Administrador.Master" AutoEventWireup="true" CodeBehind="AdministradorHome.aspx.cs" Inherits="jgghg.Pages.AdministradorHome" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque quidem sapiente alias dolores expedita, molestiae similique dignissimos at totam quia dolor minus quasi! Vero dolor dolores possimus saepe molestias dolorum?</div>
       <div>Enim alias pariatur similique doloremque tenetur tempora quis excepturi error minus repellendus natus illo debitis soluta at blanditiis cum, accusamus. Beatae voluptatem, provident architecto error adipisci officiis eaque id, cumque.</div>
       <div>Odio aliquid, impedit sint eligendi magnam ex similique reprehenderit iste at exercitationem minima accusamus. Iure non distinctio incidunt obcaecati accusamus accusantium magni tempore alias deserunt blanditiis corrupti in aliquam, explicabo.</div>
       <div>Blanditiis accusantium reprehenderit, cumque dolorem illo magnam corrupti dolorum incidunt eveniet atque officia, vitae deleniti. Doloremque facere sequi ea? Sequi veritatis repellat suscipit obcaecati cumque necessitatibus, deleniti laborum alias soluta?</div>
       <div>Iste numquam libero quibusdam, ratione quam ea dolorem, tenetur aliquam est vitae, provident. Itaque sint reprehenderit dicta atque id. Corporis consequuntur, quod temporibus reprehenderit doloremque optio sint odio, numquam quo.</div>
       <div>Labore iste numquam enim voluptate eligendi, eos aperiam quam voluptas suscipit atque quisquam iusto maiores, neque repellendus laboriosam cum vitae iure. Eum esse voluptate non necessitatibus assumenda repudiandae nisi sit.</div>
       <div>Provident iste ea iusto fugit, animi aut. Quis maiores dicta, iusto dolorum accusantium consectetur. Eligendi fugit vitae, dicta placeat soluta, sunt nostrum tempora ducimus reiciendis sed nam recusandae. Dolores, aut.</div>
       <div>Voluptatum facere dicta iure sed ab culpa delectus quas quia mollitia totam earum aliquam maiores itaque similique, impedit dolores cumque eos quisquam sequi ad distinctio placeat numquam esse. Unde, reprehenderit.</div>
       <div>Voluptatibus delectus harum obcaecati quibusdam eos, placeat pariatur, commodi nisi similique enim itaque. Omnis tempora aspernatur eos vero, perferendis cupiditate facilis nesciunt modi ullam quaerat numquam quod assumenda. Distinctio, a.</div>
       <div>Quidem inventore delectus fuga modi facere labore, quam cumque ipsa dolorum aliquid iusto expedita laudantium fugit rerum, deleniti dolores! Accusantium, illum amet facilis autem ipsum nemo perferendis modi esse porro.</div>
       <div>Dolore placeat quas error et commodi itaque aperiam neque voluptatum rerum repellendus expedita minima assumenda, ea ipsa ullam, quia modi. Consequuntur dolores labore perferendis veritatis ducimus delectus eligendi ex quo.</div>
       <div>Accusantium illo adipisci quam aperiam minus excepturi veritatis dicta! Ex officia vero nemo laudantium! Porro maiores perferendis labore, nobis, eum praesentium. Enim accusantium nisi perspiciatis culpa? Aliquid labore quam quasi.</div>
       <div>Reprehenderit earum ad quia voluptatum consectetur, provident, nesciunt facilis reiciendis. Non quia fuga ut quibusdam tempore omnis placeat aperiam fugit vel veniam. Perspiciatis accusamus pariatur, saepe officia, iure ipsum nam.</div>
       <div>Tempore accusamus architecto ad qui iusto in, placeat ipsum quae molestias saepe necessitatibus, nesciunt deleniti dicta perferendis adipisci ullam. Repudiandae optio earum expedita architecto, harum reprehenderit nihil ducimus cumque, nostrum!</div>
       <div>Modi laboriosam accusantium est eos necessitatibus a. Maiores iure minus, quaerat! Pariatur quis, veniam blanditiis dolore dolorum doloribus. Sapiente rem enim quisquam, porro, magnam sit accusantium ut voluptates. Commodi, saepe!</div>
       <div>Aspernatur a voluptas exercitationem eligendi expedita voluptatem nesciunt, provident reprehenderit. Nobis enim quisquam quidem autem rerum asperiores officiis minus, optio officia praesentium deserunt dolorum amet, voluptate, incidunt quibusdam cum molestiae.</div>
       <div>Aliquam officia, voluptas odio illum voluptatem corporis temporibus unde quia vero neque quam, voluptatum obcaecati placeat. Mollitia repellat optio labore, amet earum quibusdam consequatur quo fugit alias. Laboriosam placeat, ratione.</div>
       <div>Facere aspernatur numquam enim, culpa officiis dolorum iste corporis ad voluptatum aliquam rem doloremque maiores, nisi quam autem odit fugit beatae et consequatur! Id minus repudiandae, inventore vel ratione ipsa.</div>
       <div>Nostrum rerum excepturi aspernatur corrupti incidunt, laboriosam quos voluptas accusantium, ea quidem provident repellendus consequuntur beatae ipsum ratione fugit itaque quasi sunt. Praesentium adipisci, laudantium vitae aperiam soluta dolores ipsa.</div>
       <div>Corrupti deleniti nisi impedit quam, debitis sunt cupiditate omnis doloremque illo voluptate laudantium id doloribus quidem illum rerum culpa, qui cumque, velit tempore suscipit et amet aut dignissimos sed itaque.</div>
</asp:Content>
